### PR TITLE
Fix package.json main script path

### PR DESCRIPTION
**Pull request by jvanbrug**
Update `main` script path in `package.json` to reference `src/`, not `lib/`.

### CODE REVIEW

**Comment by TrySound** [comment]
@jvanbrug `src` is es2015 code which doesn't work in all environments. `lib` contains code processed with babel, `es` contains processed code but with es2015-modules. Your PR doesn't make sense.

**Comment by mxstbr** [comment]
The current behaviour is correct, as @TrySound mentioned, we want to give users access to the processed code, not the source! If users don't have an ES* transpiler and we only give them access to the source, they aren't able to use it, which we want to avoid.

Thanks for taking the time to submit this PR, we appreciate it a lot!

**Comment by jvanbrug** [comment]
Noob PR, thanks for the insight!

**Comment by gaearon** [comment]
No problem. Thanks for taking the time!

**Pull request closed without merging**
