### PR TITLE
Add reference to backbone-redux-migrator

### PR DESCRIPTION
**Pull request by naugtur**
I've recently found a new migration path and my colleague at work successfully introduced it to an existing project. 

This document was not very optimistic about the possibility of migration when I started researching it. I hope others can use the new migration path to escape dying Backbone ecosystem.

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by naugtur** [comment]
Did I need to do anything to get this published? It didn't show up automatically...

**Comment by markerikson** [comment]
We still don't have the docs set up to auto-republish after commits that modify them.  It'll get included the next time we get around to re-publishing them.  (Hopefully sooner rather than later :)  )

**Comment by timdorr** [comment]
Now that I [sped up the build so much](https://twitter.com/timdorr/status/837760279614275586), I should probably get on that...

**Comment by naugtur** [comment]
Hi, me again.

I hate to push you guys, but the people who are still stuck on backbone are suffering out there ;)

**Comment by timdorr** [comment]
Sure, I pushed that out now.

**Pull request merged**
