### PR TITLE
Added redux-bootstrap to utilities

### PR DESCRIPTION
**Pull request by remojansen**
HI guys,

Redux-bootstrap utility can be used to initialize Redux applications with ease:

```
import bootstrap from "redux-bootstrap";
import routes from "./routes";
import thunk from "redux-thunk";
import * as createLogger from "redux-logger";
import usersReducer from "./reducers/usersReducer";
import reposReducer from "./reducers/reposReducer";

bootstrap({
    container: "root",                    // optional
    initialState: {},                     // optional
    middlewares: [thunk, createLogger()], // optional
    reducers: {
        usersReducer,
        reposReducer,
    },
    routes: routes
});
```

You can learn more about it at [here](https://github.com/remojansen/redux-bootstrap/blob/master/README.md).

Thanks!

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks. I’ll leave this open until there are more users and initial issues are solved.

**Comment by remojansen** [comment]
Thanks!. I will be supporting it :smile:

**Comment by jokeyrhyme** [comment]
@gaearon: @remojansen and I have sorted out pluggable history, server-side rendering, and an efficient `syncHistoryWithStore()` selector. Besides getting broader acceptance, can you think of anything obvious that we haven't covered? Cheers!

**Comment by timdorr** [comment]
Seems like it's got some legs 😄  Thanks!

**Pull request merged**
