### PR TITLE
Move ActionTypes to a private export

### PR DESCRIPTION
**Pull request by timdorr**
For the first action item of #1342.

### CODE REVIEW

**Comment by mxstbr** [comment]
Pretty sure we can merge this, see https://github.com/reactjs/redux/issues/1342#issuecomment-178145367

**Comment by gaearon** [comment]
Yes, but I’d like to merge all breaking changes to master at the same time before cutting a release. It is weird when breaking changes linger in master. I’m fine with starting a `4.x` branch where we do that though.

**Comment by timdorr** [comment]
We have a `next` branch on router.

**Comment by gaearon** [comment]
Sounds reasonable :+

**Comment by timdorr** [comment]
If you want, I can create a `next` branch and reopen this against that branch.

**Comment by gaearon** [comment]
:+1:

**Pull request closed without merging**
