### PR TITLE
Port examples to use Create React App

### PR DESCRIPTION
**Pull request by gaearon**
Work in progress.
This is a good opportunity to dogfood the tool!

### CODE REVIEW

**Comment by mxstbr** [comment]
RIP #1800

**Comment by gaearon** [comment]
😅

**Comment by canibanoglu** [comment]
@gaearon I know you're working on this and I have a suggested improvement. Should I go ahead an create a PR myself?

**Comment by gaearon** [comment]
What kind of improvement?

**Comment by canibanoglu** [comment]
Well improvement might not really be the word :) There's an unused import in todo-with-undo's index.js file: `import 'babel-polyfill'`. 

Another thing that caught my eye is the use of double quotes in `components/Footer.js`. Everywhere strings are enclosed in single quotes but in this file they are enclosed in double quotes. Props passed to `FilterLink` are probably intentional but I'm not so sure about the "separator" strings `{", "}` and `{" "}`.

**Comment by gaearon** [comment]
>There's an unused import in todo-with-undo's index.js file: import 'babel-polyfill'.

Feel free to send a PR for this.

>Another thing that caught my eye is the use of double quotes in components/Footer.js. Everywhere strings are enclosed in single quotes but in this file they are enclosed in double quotes. Props passed to FilterLink are probably intentional but I'm not so sure about the "separator" strings {", "} and {" "}.

I'll clean up style according to our lint config before merging.

**Comment by canibanoglu** [comment]
Great, thanks a lot for the help

**Comment by timdorr** [comment]
Hmm, not sure why that last change didn't fix it. Well, I tried!

**Comment by canibanoglu** [comment]
I have noticed that every component under the shopping cart example is a stateless component but they all are defined with the `class` syntax instead of functional components. I would love to convert everything to functional components if that is alright.

**Comment by canibanoglu** [comment]
I found some more stuff in the shopping cart example. But I don't really feel comfortable hijacking @gaearon's PR with my questions all the time and I will go through all of the examples in detail during the weekend. 
Should I just create PRs for each example and then my proposed changes could be reviewed under those? Or maybe under issues?
I would greatly appreciate your input on this :)

**Comment by timdorr** [comment]
@canibanoglu I left the branch in #1800 untouched. So if you see anything in there you want to pull from, that's fine. We'll do a PR to update the examples after this one cleans up the build infrastructure.

**Comment by canibanoglu** [comment]
Alright I'll send my PRs to that branch then. Thank you very much for you help!

**Comment by gaearon** [comment]
Going to Just Do This.
If something’s wrong please fix 😄 .

**Pull request merged**
