### PR TITLE
Build umd with rollup

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/reactjs/redux/issues/2245

### CODE REVIEW

**Comment by TrySound** [comment]
40 461 b -> 27 793 b
10 738 b -> 7 503 b

**Comment by gaearon** [comment]
CI seems to fail because of ES3ify check.
But while we're at it, why does the compiled bundle have `.default` anywhere at all?

**Comment by TrySound** [comment]
Nice catch. symbol-observable has only `jsnext:main` which is disabled by default.

**Comment by timdorr** [comment]
@gaearon 
> But while we're at it, why does the compiled bundle have .default anywhere at all?
That is the way Babel 6 handles `export default`. @kentcdodds [wrote about it](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.qrp1xf6p3), but here's why:
```js
// foo.js
const foo = {baz: 42, bar: false}
export default foo
// bar.js
import {baz} from './foo'
```
That is against the spec (though it may have changed since 6.0.0), so they "broke" that behavior to fix the spec. Hence, all defaults are exported in the `default` property of the module.

**Comment by gaearon** [comment]
Right, but if we're bundling with rollup, we need to let it handle ES modules instead of Babel. So we should change the rollup env to *not* do the commonjs transform.

**Comment by gaearon** [comment]
@TrySound Can you post resulting bundles as gists for comparison?

**Comment by timdorr** [comment]
BTW, we're down to:
```
26843 dist/redux.js
 7159 dist/redux.min.js
```
👍 

Here's the latest build artifacts for easy perusal: https://gist.github.com/timdorr/73a8d368c1d0c3d3c83aa73af8f02cbe

**Comment by timdorr** [comment]
LGTM. Most of the cost savings are from the babel import/export transforms and the inter-module imports (`__webpack_require__` stuff). Surprisingly hefty! Here's hoping webpack 2 can add scope hoisting soon...

**Comment by gaearon** [comment]
[This part](https://gist.github.com/timdorr/73a8d368c1d0c3d3c83aa73af8f02cbe#file-redux-js-L512) worries me a little. Does it inline in prod build?

**Comment by TrySound** [comment]
Yeah. This increases bundle. Weird behavior.

**Comment by gaearon** [comment]
Could be https://github.com/reactjs/redux/issues/2244, I'm not sure if it was fixed yet in master.

**Comment by timdorr** [comment]
Now:
```
26843 dist/redux.js
 7023 dist/redux.min.js
```
Keep going!

**Comment by TrySound** [comment]
@gaearon Yeah. Current min release is smaller because of that thing. Inference with code elimination is too hard :) That PR should be reverted.

**Comment by timdorr** [comment]
I'll merge it in here and then merge in this PR. The reason for #2030 are something you can fix with tooling.

**Comment by TrySound** [comment]
Do you guys want to release it as 3.* or 4.*?

**Comment by timdorr** [comment]
@TrySound Can you enable contributor pushing to your branch? Should be a checkbox at the top of the PR.

**Comment by timdorr** [comment]
Once I can push it, reverting that takes us down to:
```
26636 dist/redux.js
 5827 dist/redux.min.js
```
Now we're cooking.

**Comment by TrySound** [comment]
Yay!

@timdorr It's enabled.

**Comment by timdorr** [comment]
Cool, I think we're good. This doesn't change anything outside of the UMD build and does so in entirely a compatible way, so I think it only needs a patch version. Correct me if I'm wrong, otherwise I'll push this as 3.6.1. I don't believe we've had any other non-docs/examples updates since that release.

**Comment by gaearon** [comment]
It's probably safe as a patch. Maybe as a minor for a tiny bit of extra safety.

**Comment by TrySound** [comment]
Okay. I just would like to remove `jsnext:main` which is legacy. Rollup uses `module` field now. But guys still add this field looking at this and similar packages. But this will be breaking change.

**Comment by timdorr** [comment]
Go ahead and do that against the `next` branch, which is our target for 4.0 stuff. 

AFAIK, [webpack is following suit](https://webpack.js.org/configuration/resolve/#resolve-mainfields), so that should be a low-impact breaking change for most folks.

**Comment by timdorr** [comment]
BTW, thanks for the hustle on this!

**Pull request merged**
