### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by gaearon** [comment]
Let’s just change it to `2015–present`.

**Comment by vaibhavmule** [comment]
@gaearon Do you want me to Squash this commit or fresh commit with new branch?

**Comment by gaearon** [comment]
It’s fine, Github now squashes them 😄

**Comment by vaibhavmule** [comment]
Oh really, Good to hear that.

Thanks for merging my pull request.

**Pull request merged**
