### PR TITLE
docs(NextSteps): Next steps page - WIP

### PR DESCRIPTION
**Pull request by codedavinci**
Based on the roadmap given, I came up with a sort of step-by-step progress and things to consider before creating a project and while working on it. 

I have used some of the articles from @markerikson's repository called  **React/Redux links list** as he's previously requested. 

Waiting for feedback. 

Cheers,

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks for working on this!  I'll try to go through it in the next couple days.

**Comment by codedavinci** [comment]
Sounds perfect !

Thank you.

**Comment by codedavinci** [comment]
Hello @markerikson, just following up on this `PR`, wondering if you had some time to review it.  :)

Kindly,

**Comment by markerikson** [comment]
Hi.  No, afraid I haven't.  Still on my radar, and I'll try to get to it shortly.  Sorry for the delay!

**Comment by timdorr** [comment]
I went through and cleaned up a bunch of things. Mostly grammar and formatting issues.

**Comment by codedavinci** [comment]
Thank you @timdorr for proofreading it :) !

**Comment by timdorr** [comment]
Fixed the merge conflicts. @markerikson What do you think?

**Comment by markerikson** [comment]
It's a decent start, but I'm thinking I'd really like to see more of a "real world tutorial" section.

Still, this at least gives us _something_ for that page.  Sure.

**Pull request merged**
