### PR TITLE
Allowing nested action creators in bindActionCreators

### PR DESCRIPTION
**Pull request by lmuntaner**
- New function mapNestedValues using traverse
- bindActionCreators uses mapNestedValues
- new specs for new feature

### CODE REVIEW

**Comment by gaearon** [comment]
Thank you for taking time to contribute!

Alas, I would rather *not* take this because deeply nested action creators will be slower to bind (unless you only do it once), and we don’t want to encourage slow patterns. I am also concerned about `action.js` exporting some object by mistake which would get interpreted by `bindActionCreators` as something that needs deep traversal which, with unlucky circumstances, can be very expensive but easy to overlook.

This has been discussed before and it’s fairly easy to implement in userland, so you are welcome to publish a separate package that implements this.

Previous discussions:

* https://github.com/reactjs/redux/issues/716
* https://github.com/reactjs/redux/issues/1064
* https://github.com/reactjs/react-redux/issues/132#issuecomment-144780772

Sorry!

**Comment by lmuntaner** [comment]
Thanks for taking time to go over the PR and responding.

I understand your concerns.

**Comment by timrichd** [comment]
Wheres that separate package?

**Comment by markerikson** [comment]
Not sure the PR author actually published one, but you can see the code changes in the diff.  Also, https://github.com/stutrek/redux-action-wrapper looks like an equivalent approach.

**Comment by lmuntaner** [comment]
Yep, we never publish any package regarding this, sorry.

**Comment by stegano** [comment]
> Thank you for taking time to contribute!
> 
> Alas, I would rather _not_ take this because deeply nested action creators will be slower to bind (unless you only do it once), and we don’t want to encourage slow patterns. I am also concerned about somebody’s `actions.js` exporting some object by mistake which would get interpreted by `bindActionCreators` as something that needs deep traversal which, with unlucky circumstances, can be very expensive but easy to overlook.
> 
> This has been discussed before and it’s fairly easy to implement in userland, so you are welcome to publish a separate package that implements this.
> 
> Previous discussions:
> 
> * #716
> * #1064
> * [reduxjs/react-redux#132 (comment)](https://github.com/reduxjs/react-redux/issues/132#issuecomment-144780772)
> 
> Sorry!

Hi @gaearon 

Could you reconsider allowing nested objects?
(i'm not good at english, please understanding 😅)

Unlike in the past, we can detect and prevent wrong action objects from being bound in advance by using type system such as Typescript or flow.

Libraries like [_typesafe-actions_](https://github.com/piotrwitek/typesafe-actions) make utilizing of nested object actions(e.g. createAsyncAction) but, use bindActionCreators you must manually list all actions.

I respect your opinion, but this issue too old, so i'll try request.

Thanks and Happy New Year 😀

**Comment by markerikson** [comment]
@stegano Dan hasn't worked on Redux in years, and waking up a years-old issue thread just to ping someone is poor etiquette. Please don't do that.

`bindActionCreators` was really built to serve the needs of `connect`.  Now that we have the React-Redux hooks API, it's much less important.

We have no plans to change the core API at this point.

**Pull request closed without merging**
