### PR TITLE
Shopping cart example updates

### PR DESCRIPTION
**Pull request by canibanoglu**
The pull request I mentioned in #1883. I would appreciate feedback on this. If I have missed anything, please let me know and I will get on it right away.

### CODE REVIEW

**Comment by timdorr** [comment]
Good work! Thanks!

**Comment by timdorr** [comment]
Oh, whoops, this is against the wrong branch. It needs to be against create-react-app. Sorry about that.

**Comment by canibanoglu** [comment]
Huh, I thought it should be against this one since you told me that once Dan is finished this one would be merged into that one. Should I go ahead and create a PR against `create-react-app`?

**Comment by timdorr** [comment]
Nope, create-react-app replaces the previous one. You should make sure that your branch is rebased against create-react-app, as just opening a PR will include all the prior changes on this branch that we don't want to add yet.

**Pull request merged**
