### PR TITLE
Fix(dependencies) Update symbol-observable requirement to 1.0.2

### PR DESCRIPTION
**Pull request by btd**

### CODE REVIEW

**Comment by btd** [comment]
Test failed because symbol-observable used 'default' (as usually proceed by babel) and es3 checker detects this.

Actual patch:
```diff
Index: dist\redux.js
===================================================================
--- dist\redux.js
+++ dist\redux.js
@@ -917,9 +917,9 @@
 	var _ponyfill = __webpack_require__(14);
 
 	var _ponyfill2 = _interopRequireDefault(_ponyfill);
 
-	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
+	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
 
 	var root = undefined; /* global window */
 
 	if (typeof global !== 'undefined') {
@@ -927,10 +927,10 @@
 	} else if (typeof window !== 'undefined') {
 		root = window;
 	}
 
-	var result = (0, _ponyfill2.default)(root);
-	exports.default = result;
+	var result = (0, _ponyfill2["default"])(root);
+	exports["default"] = result;
 	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))
 
 /***/ },
 /* 14 */
@@ -940,9 +940,9 @@
 
 	Object.defineProperty(exports, "__esModule", {
 		value: true
 	});
-	exports.default = symbolObservablePonyfill;
+	exports["default"] = symbolObservablePonyfill;
 	function symbolObservablePonyfill(root) {
 		var result;
 		var _Symbol = root.Symbol;
 

```

**Comment by gaearon** [comment]
So, should this be fixed in `symbol-observable`?

**Comment by SimenB** [comment]
I opened a PR for it over there (blesh/symbol-observable#22)

Cool that the module does its job! 😀

**Comment by btd** [comment]
@SimenB thanks. I actually was not sure, if symbol-observable commiters interested in es3 syntax support. Waiting now for merging.

**Comment by asiniy** [comment]
:+1: @btd you are 2 days faster than me :tongue:

**Comment by gaearon** [comment]
I think https://github.com/blesh/symbol-observable/pull/22 should get merged first?

**Comment by gaearon** [comment]
Oops sorry it was already mentioned in this thread 😛

**Comment by btd** [comment]
@gaearon i updated commit to 1.0.2

**Comment by timdorr** [comment]
Thanks!

**Comment by btd** [comment]
@timdorr can i get this published to npm?

**Pull request merged**
