### PR TITLE
Fixed 'is undefined' error and prop checking in Async example

### PR DESCRIPTION
**Pull request by leiming**
Fix the same error as #2464 #2459  for Async example.

If it is acceptable, I will fix all examples which includes #2469

### CODE REVIEW

**Comment by timdorr** [comment]
Does our/CRA's eslint config not support class properties and statics?

**Comment by leiming** [comment]
Thanks for replying, @timdorr.

I think CRA's ESLint has supported [babel-plugin-transform-class-properties](https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L13). However it doesn't take effort in example cases. 

I try to add a `.eslintrc` file in `redux/examples/real-world/src`, and even install both `babel-plugin-transform-class-properties` and `babel-preset-react-app`:

```json
{
  "extends": "react-app",
  "plugins": ["transform-class-properties"]
}
```

then:

```bash
cd redux/examples/real-world/src
yarn add -D babel-preset-react-app babel-plugin-transform-class-properties
yarn start
```
It still throw error, seems ignore all ESLint config:

```
Failed to compile.

./src/containers/App.js
  Line 9:   'propTypes' is not defined           no-undef
  Line 18:  'handleDismissClick' is not defined  no-undef
  Line 23:  'handleChange' is not defined        no-undef

Search for the keywords to learn more about each error.
```

**Comment by timdorr** [comment]
Oh, this looks like it's coming from the eslint install at the root of the repo: https://github.com/facebookincubator/create-react-app/issues/2604#issuecomment-311168618

Downgrading back to eslint 3.x should fix it, I believe.

**Comment by leiming** [comment]
OK, I will keep track of https://github.com/facebookincubator/create-react-app/issues/2644

**Comment by timdorr** [comment]
Since it's something that will be fixed upstream, I'll wait on that fix before making code changes here. Thanks for bringing this to our attention!

**Pull request closed without merging**
