### PR TITLE
Add isomorphic-fetch and lodash

### PR DESCRIPTION
**Pull request by mdulac**

### CODE REVIEW

**Comment by mdulac** [comment]
The real-world project does not works due to a lack of those two librairies : isomorphic-fetch and lodash. I had to execute extra "npm install" for these two librairies to make this project work

**Comment by gaearon** [comment]
Interesting. I wonder why Travis doesn't fail on master. Can you take a look at previous build logs?

**Comment by timdorr** [comment]
Might be caching on Travis's end. Maybe try busting the cache and rebuilding?

**Comment by gaearon** [comment]
Thanks. I’ll remove `isomorphic-fetch` separately because Create React App already includes a polyfill for it.

**Pull request merged**
