### PR TITLE
Add redux-cut to middleware section

### PR DESCRIPTION
**Pull request by leonaves**
Is this really cheeky? 😜

### CODE REVIEW

**Comment by gaearon** [comment]
Let’s wait for some more users, issues and versions?

**Comment by leonaves** [comment]
Yeah fair I thought you might say something like that! No worries!

**Comment by gaearon** [comment]
Don’t be shy to submit again. I just think some more real world usage would be needed so we don’t recommend something that might change the API soon.

**Comment by markerikson** [comment]
FWIW, I do have it listed in my Redux addons catalog: https://github.com/markerikson/redux-ecosystem-links/blob/master/middleware.md#action-grouping-and-interception

**Pull request closed without merging**
