### PR TITLE
Fix TS definitions test for new Dispatch typing

### PR DESCRIPTION
**Pull request by pelotom**

### CODE REVIEW

**Comment by timdorr** [comment]
BTW, there is another PR (that I busted with `next` updates just now), that has a similar, but different set of fixes: https://github.com/reactjs/redux/pull/2671/commits/b9278d1e9daef210208a4faae20266c6a96f3a05

Any thoughts on the comparison between the two?

**Comment by pelotom** [comment]
By and large it's equivalent, but these definitions aren't quite right:

```ts
// dispatch.ts
declare module "../../" {
  export interface Dispatch<D = Action> {
    <R>(asyncAction: (dispatch: Dispatch<D>, getState: () => D) => R): R;
    // ^ `getState()` should not return the action type `D`
  }
}
```

```ts
// middleware.ts
declare module "../../" {
    export interface Dispatch<D> {
        <R,S>(asyncAction: (dispatch: Dispatch<D>, getState: () => S) => R): R;
        // ^ `getState()` should not be parameterized by the state type `S`; the type
        // of the state is not determined by the caller
    }
}
```

**Comment by timdorr** [comment]
Thanks. I'm starting to get my bearings with TS stuff, but our typings are *really* dense and I need some hand-holding :)

I think this looks good. Since we're now passing, this should get my other PRs unblocked. Thank you!

**Comment by pelotom** [comment]
No problem, looking forward to seeing these typings on `master`!

**Pull request merged**
