### PR TITLE
Fixed 'is undefined' error and prop checking in Counter example

### PR DESCRIPTION
**Pull request by Krizzu**
Added method binding in constructor + prop checking.

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by heracek** [comment]
@Krizzu Just out of curiosity, why is binding in constructor better?

**Comment by Krizzu** [comment]
It's not like it's better, but changed it because `eslint` was throwing 'undefined` errors.

**Comment by timdorr** [comment]
This is actually caused by the upgrade to eslint 4.0 at the top level and CRA using the wrong version: https://github.com/facebookincubator/create-react-app/issues/2604#issuecomment-311168618. 

I'll likely revert this once https://github.com/facebookincubator/create-react-app/issues/2644 lands.

**Comment by heracek** [comment]
Ok, thanks!

**Pull request merged**
