### PR TITLE
Improve typings for Middleware

### PR DESCRIPTION
**Pull request by davidka**
This PR fixes Issue #2481

### CODE REVIEW

**Comment by timdorr** [comment]
Can I get some eyes on this to confirm this fixes the issue? Thanks!

**Comment by tbo** [comment]
This doesn't fix the issue for me. I get additional error messages:

```
    ERROR in [...]/node_modules/redux-thunk/index.d.ts
    (14,22): error TS2314: Generic type 'Middleware<S>' requires 1 type argument(s).
    ERROR in [...]/node_modules/redux-thunk/index.d.ts
    (15,42): error TS2314: Generic type 'Middleware<S>' requires 1 type argument(s).
    ERROR in [...]/shared/createStore.ts
    (27,3): error TS2345: Argument of type '(store: MiddlewareAPI<IState>) => (next: any) => (action: any) => any' is not assignable to parameter
 of type 'GenericMiddleware'.
      Types of parameters 'store' and 'api' are incompatible.
        Type 'MiddlewareAPI<S>' is not assignable to type 'MiddlewareAPI<IState>'.
          Type 'S' is not assignable to type 'IState'.
```

**Comment by aikoven** [comment]
This will break any existing usage of `Middleware` type since it now became a generic type.

We should rather add a new type without touching existing ones.

**Comment by davidka** [comment]
I could do it the other way and introduce a new type SpecificMiddleware: 

```
export interface SpecificMiddleware<S> {
  (api: MiddlewareAPI<S>): (next: Dispatch<S>) => Dispatch<S>;
}

export interface Middleware {
  <S>(api: MiddlewareAPI<S>): (next: Dispatch<S>) => Dispatch<S>;
}
```

But if we would update the typescript dependency from 1.8.0 to 2.4.2, we could make it even more elegant with only one type: 

```
export interface Middleware<T=any> {
    <S>(api: MiddlewareAPI<S>): (next: Dispatch<S>) => Dispatch<S>;
    (api: MiddlewareAPI<T>): (next: Dispatch<T>) => Dispatch<T>;
  }
```

@timdorr Does anything stand against?

**Comment by tbo** [comment]
@davidka I don't think we should force everybody to use the latest typescript version. Some people might run into problems with unresolved conflicts in other dependencies or have other restrictions in place.

**Comment by davidka** [comment]
@tbo yeah that make sense. 
I have now added an extra typing `SpecificMiddleware` which accepts a specific type.
But I do not really like that.

**Comment by davidka** [comment]
@timdorr Could we merge that?

**Comment by tbo** [comment]
I retested this and it still doesn't fix the issue for me. Maybe it is limited to my specific setup, so I would suggest, that somebody else should test this as well.

**Comment by timdorr** [comment]
Superceded by #2563

**Pull request closed without merging**
