### PR TITLE
Update "Writing Tests" doc to use Enzyme

### LINKED ISSUE #1679: Add Enzyme to redux testing docs
In #1481, you suggested using Enzyme in tests, and I can see that people helped take this on and get the example apps set up with Enzyme testing. However, Enzyme is not used in the example in [the Redux "Writing Tests" doc](http://redux.js.org/docs/recipes/WritingTests.html).

Do you want me to add it there? I can submit a PR for you to check out. For the prose section, I plan to say something like "Facebook provides a basic helper library called [ReactTestUtils](https://facebook.github.io/react/docs/test-utils.html) for testing React components. Here we'll show how to test your component using Airbnb's [Enzyme](http://airbnb.io/enzyme/), which uses ReactTestUtils internally, and makes our job of testing easier and provides additional functionality."

PS: I read the guidelines for contributing and wasn't sure if I should add this to #1481 or start a new case. Sorry if I chose wrong. :-)

### PR DESCRIPTION
**Pull request by tylercollier**
Fixes #1679.

Notes:

* I didn't bother updating all tests in the TODOMVC app because it's (supposedly) already being worked on, see #1471 and #1493 (and they were even removed in #1480), as well as #1481 claiming that the TODOMVC app will be "completely replaced". If you have changed your mind on that (I'm not sure where that decision came from and that was from 2 months ago), let me know and I'm happy to update the rest of the tests to use Enzyme.
* I removed mention of an old issue with `setState()` that Enzyme automatically handles.

### CODE REVIEW

**Comment by timdorr** [comment]
Looks like there are some conflicts. Can you rebase against master? Thanks!

**Comment by tylercollier** [comment]
Ha! Someone had changed a single sentence of a sentence I had also changed by removing it.

Anyway, I have rebased as requested.

**Comment by timdorr** [comment]
Sorry, I missed the todomvc updates included here. Can you remove those? We can track that work in #1493 or another PR if that one doesn't pick back up again.

**Comment by tylercollier** [comment]
Ok, done.

**Comment by tylercollier** [comment]
Ping?

**Comment by tylercollier** [comment]
Ping @timdorr @gaearon 

Dan, I'm pinging you because:

1. I'm not sure of Tim's status/availability
1. Your original "go ahead" on #1679 
1. The quality of Redux's docs IS Redux, in my opinion, and I think yours too. Redux is powerful because it's simple. The library is small; it's explaining how to use it that matters. The quality of the doc is what made me start with Redux over Flux way back when.

**Comment by markerikson** [comment]
Looks reasonable at first glance to me.  If no one else responds in another day or so, ping me in here and I'll accept it.

**Comment by timdorr** [comment]
Let's do it!

**Comment by tylercollier** [comment]
I'm looking at http://redux.js.org/docs/recipes/WritingTests.html and don't see the changes. No mention of Enzyme.

I'm guessing it's due to the fact that the code isn't in the gh-pages branch? I'm sorry, perhaps that means that I should have made changes in my gh-pages branch, and if so, I'm sorry for my rookie mistake (we should add a note in CONTRIBUTING :-). Would you like me to do that and submit another pull request, or can you make the fix?

**Comment by markerikson** [comment]
The docs have to be re-published once the Markdown files are updated.  I'll try to get to it this evening.  (I want to do so anyway, because I don't think the current published version includes the plugin I added to the Gitbook build to fix the anchor link jumping behavior.)

**Comment by tylercollier** [comment]
It's been a month. Is it worth publishing now?

**Comment by timdorr** [comment]
@tylercollier Yeah, it's been a while (2 months!). Just pushed an updated build now.

**Comment by markerikson** [comment]
@timdorr , do you have your Gitbook setup updated with the "fix the page jumping" plugin I added when I set up the FAQ page?  Looks like that's still not working right now.

**Comment by timdorr** [comment]
Nope, but what's the name of the plugin exactly? I can make sure it's added into the project.

**Comment by markerikson** [comment]
It is actually already listed - I updated book.json after I published the initial FAQ page.  It's https://github.com/sifue/gitbook-plugin-anker-enable , which basically just does a `setTimeout(jumpBackToAnchor, 300)`.  

I had it installed in my local Gitbook setup and did a publish with it, but Gitbook must not complain if you don't have it installed or something.

**Comment by timdorr** [comment]
Gitbook auto-installs requested plugins. `book.json` acts like `package.json`, essentially:
```
info: No version specified, resolve plugin anker-enable
info: install plugin anker-enable from npm (gitbook-plugin-anker-enable) with version 0.0.4
gitbook-plugin-anker-enable@0.0.4 node_modules/gitbook-plugin-anker-enable
info: >> plugin anker-enable installed with success
```

**Pull request merged**
