### PR TITLE
Add "testEnvironment" to jest config in package.json.

### PR DESCRIPTION
**Pull request by burnmaniac**
This is the fix for #2921, also my first official OSS contribution. I hope I did everything all right.

Thank you!

### CODE REVIEW

**Comment by markerikson** [comment]
Hmm.  To be fair, it looks as if that's directly related to using an older version of Node (per https://github.com/facebook/jest/issues/5276 and https://github.com/standard-things/esm/issues/210 ).

Still, I don't see any reason to _not_ add that flag to `package.json`.  @timdorr  ?

**Comment by burnmaniac** [comment]
Just in case the flag didn't break the tests on newer versions of Node, I know that Travis will do that also, but I've installed newer version of Node (8.11.1 which is the LTS at this moment) and run the tests with the `testEnvironment` flag. All the tests passed.

**Comment by timdorr** [comment]
Just FYI: The suite is failing because of some flow stuff that's out of date, not this change.

I'd actually *want* the suite to fail on that old of a version. It serves as a warning to upgrade (even though it's somewhat opaque). If you're developing a code contribution to Redux, you need to be using the latest npm and should be on an updated node version. That's what I use for publishing and what we use for testing.

Perhaps we should add an `engines` section to the package.json instead?

**Comment by burnmaniac** [comment]
I didn't think of it that way. I didn't want to use that Node version, I just installed it using `apt`. Didn't even check which version was it.

I guess I should first find out on which Node version everything works, then add it like this?

```
{
    engines: {
        "node": ">=6.0.0" // Or which ever version I find minimal
    }
}
```

**Comment by timdorr** [comment]
Actually, I realized that's incorrect. That would apply to the published package, not just the dev environment. We still support node 4 and earlier, since there isn't anything wacky like async or generators in there. 

Not sure what the best option is. I lean towards doing nothing and erroing out for older node versions. Not as nice, but less messy for users.

**Comment by burnmaniac** [comment]
I agree. Feel free to close pull request. 👍

**Pull request closed without merging**
