### PR TITLE
Doc fix: updateObjectInArray replaces with new value, not an obj.

### PR DESCRIPTION
**Pull request by dlrice**

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by markerikson** [comment]
Actually, I really did intend the original usage.  The intent was the `action.item` might be a partial object, not the entire thing.  The edited version might be the way you'd want to do it if your action always includes the entire new item, but that's not what I had in mind when I wrote this.

Appreciate the PR, but I'm going to revert this back to the original version.

**Comment by timdorr** [comment]
Ah, thanks. I wasn't 100% on that.

**Comment by markerikson** [comment]
Yeah, I probably didn't make it entirely clear in the writeup, but that's what I was thinking when I wrote it.

**Pull request merged**
