### PR TITLE
Simplify the definition of reducers

### PR DESCRIPTION
**Pull request by vkatsikaros**
Instead of defining reducers by what actions are not, define reducers by what they are. A reminder of what actions are is kept in the text, for education purposes.

I am not a react/redux expert so feel free to correct any errors in the new text.

However, wording is subjective and a matter of taste. So, I'll understand if you won't consider merging the change.

### CODE REVIEW

**Comment by timdorr** [comment]
LGTM. Since this is relatively important text, I'd rather get a second 👍 before merging.

**Comment by naw** [comment]
I like the direction and intent of the change. I like the first sentence. However, removing the words after "how" from the last sentence changes the meaning of the sentence. It begs the question "how what?", and the mind will fill in "how something happened" rather than "how the state changes".

**Comment by vkatsikaros** [comment]
Thanks @timdorr and @naw!

I pushed a change to address https://github.com/reactjs/redux/pull/2705#issuecomment-342996961

**Comment by timdorr** [comment]
@markerikson Any thoughts?

**Comment by timdorr** [comment]
LGTM, so I'm going to merge it in. Thanks!

**Pull request merged**
