### PR TITLE
Fat arrow functions in the counter example

### PR DESCRIPTION
**Pull request by ChrisJamesC**
With this PR I would like to propose to add more ES6-like syntax in the examples. 

This is an opinionated subject since we might want to stick with some more ES5-like syntax in order for new comers to not be intimidated by the syntax on top of redux. 

Please let me know what you think.

### CODE REVIEW

**Comment by timdorr** [comment]
This fits in well with what was leftover from #1800. Thanks!

**Comment by ChrisJamesC** [comment]
Thanks @timdorr for the quick review and for the reference to the issue!

**Comment by alexeyraspopov** [comment]
What's the purpose of using arrow function instead of class method? It seems to be noisy.

**Comment by timdorr** [comment]
@alexeyraspopov It auto binds the function. It removes the need to do manual binding like the example had before in the constructor.

**Pull request merged**
