### PR TITLE
fix code example for `generating reducers`

### PR DESCRIPTION
**Pull request by seriousManual**

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by markerikson** [comment]
FWIW, the existing example _was_ valid.  It's an ES6 object literal, with a computed key as the function name, and a function declaration directly as part of the object.

Admittedly not the easiest thing to read, but it was valid.

**Comment by timdorr** [comment]
Ah, I didn't know you could combine those two, but that makes sense.

**Comment by seriousManual** [comment]
wow, didn't know this! 
thanks for the clarification, with the added colon and fat arrow the readability might a bit better though :)

**Pull request merged**
