### PR TITLE
The better way to complement compose.

### PR DESCRIPTION
**Pull request by quanru**
It's easy to understand than the former in this way.

### CODE REVIEW

**Comment by wuct** [comment]
The new approach loses the ability to apply multiple arguments to the first composed function.

**Comment by gaearon** [comment]
I would suggest searching old pull requests for "compose". Everybody who sees that function tries to rewrite it 😅

**Comment by markerikson** [comment]
Yep.  Appreciate the PR, but there's no need for further changes to this function at this point.

**Comment by gaearon** [comment]
For the reference, see my last reply about this: https://github.com/reactjs/redux/pull/2275#issuecomment-284153667.

**Pull request closed without merging**
