### PR TITLE
Structuring reducers publish prep

### PR DESCRIPTION
**Pull request by markerikson**
Add "Structuring Reducers" pages to docs TOC, and rename reducer pages for better URLs.

### CODE REVIEW

**Comment by markerikson** [comment]
CC @timdorr 

Think this should be all that's needed to get it publishing okay.

**Comment by timdorr** [comment]
Looks like something is conflicting now?

**Comment by markerikson** [comment]
Yeah, I think one of the typo PRs I merged conflicts with the edits.  Lemme poke at this.

**Comment by markerikson** [comment]
Conflict fixed.  Should be good to go now.

**Comment by markerikson** [comment]
Schweet!

**Pull request merged**
