### PR TITLE
[WIP] refactor to eslint airbnb, remove babel-eslint

### PR DESCRIPTION
**Pull request by knowbody**
This is a work in progress on moving to `eslint-config-airbnb` and removing `babel-eslint`

#### Todo
- [x] - remove `babel-eslint`
- [x] - remove `eslint-config-rackt`
- [x] - add `eslint-config-airbnb`
- [x] - fix the linting according to airbnb style guide
- [ ] - merge awaitng PRs (as per: https://github.com/reactjs/redux/issues/1554#issuecomment-203576976), and apply new eslint config to them
- [ ] - apply new linting to the docs

@gaearon let me know if you have any feedback on this

### CODE REVIEW

**Comment by johnsoftek** [comment]
:( It was refreshing to find a project that eschewed semicolon, a la JS
Standard.

Maybe it's too late but why airbnb?

**Comment by knowbody** [comment]
@johnsoftek it's not too late, it's a work in progress. There was a discussion about semicolons somewhere, for me it seriously does not matter. I want on one project with semicolons - I'm fine, working on the other one without them - I'm fine too.

> but why airbnb?

airbnb is the most used eslint config and most developers are familiar with it. re: semicolons we can also customise the rules and switch it off, but I don't think we should do it.

**Comment by knowbody** [comment]
@gaearon it :white_check_mark: passes the tests. I will update the docs soon, ping me once the PRs you wanted to merge before this, are merged and I'll update this branch with master so we can merge it in.

**Comment by SimenB** [comment]
Anything happening here?

**Comment by timdorr** [comment]
@knowbody I'm going to do what I did in reactjs/react-redux#461 to update the config without causing so much churn (mainly to do with semicolons). Unfortunately, in projects as busy as these ones, merging in a PR with huge changes (or dealing with PRs after a huge change) is nearly impossible. So, I found that was a good compromise to keep the process sane. I hope to get to that soon!

**Pull request closed without merging**
