### PR TITLE
Update FAQ page

### PR DESCRIPTION
**Pull request by markerikson**
Split FAQ page up by category
Update each category with additional links and information

### CODE REVIEW

**Comment by markerikson** [comment]
Pinging @reactjs/redux if anyone wants to take a look-through.  If there's no immediate complaints, I'll merge this in tomorrow.

**Comment by markerikson** [comment]
Note that I kept all the existing short hashtags in the main page, and moved them to be adjacent to the TOC links to the new locations.  So, all the old hashtags will still point to a relevant spot in the page, just with an extra click's worth of indirection.

**Comment by jimbolla** [comment]
Structurally, this is definitely a big improvement.

**Comment by markerikson** [comment]
Cool.  If no other comments in the next hour or so, I'll merge.

@timdorr , you mind re-publishing the docs once this is in?  I've got other stuff I'd like to tackle atm, rather than figuring out exactly how to sort through issues publishing docs under Windows right now.

**Comment by timdorr** [comment]
Yep, I'll do that a little bit later tonight.

**Comment by mxstbr** [comment]
I like it, nice one!

**Comment by markerikson** [comment]
No further complaints, aaaaaand merging!

**Pull request merged**
