### PR TITLE
Update Ecosystem.md

### PR DESCRIPTION
**Pull request by Jackong**
add redux-authentication component

### CODE REVIEW

**Comment by markerikson** [comment]
Hmm.  Not sure this is a good fit for the Ecosystem page in the docs right now.  Please feel free to submit a PR to the [Redux Ecosystem Links](https://github.com/markerikson/redux-ecosystem-links) repo, though.

**Comment by gaearon** [comment]
Yea, we’re generally open to adding React components but only after they are already very popular independently.

**Comment by mxstbr** [comment]
Maybe also look into adding it to https://react.parts/web if it isn't there already!

**Comment by markerikson** [comment]
Actually, I think react.parts is now obsolete.  Pretty sure it was superseded by https://js.coach.

**Comment by markerikson** [comment]
Could also add it to [Awesome-Redux](https://github.com/xgrommx/awesome-redux).

**Pull request closed without merging**
