### PR TITLE
use subscribe to persist to localStorage

### PR DESCRIPTION
**Pull request by willnwhite**
more discoverable than https://github.com/reactjs/redux/pull/1608

### CODE REVIEW

**Comment by gaearon** [comment]
The wording is not entirely what I wanted. Maybe something like this?

```
You can use subscribe() to update the UI in response to state changes.
Normally you’d use a view binding library (e.g. React Redux) rather than subscribe() directly.
However it can also be handy to persist the current state in the localStorage.
```

**Comment by willnwhite** [comment]
Yep, yours is clearer.

**Comment by gaearon** [comment]
Feel free to use it in your PR or tweak it. It’s your initiative, I’m just trying to be helpful. 😉

**Comment by willnwhite** [comment]
Did I do it right? (I've never done more than one commit on a branch for a PR.)

**Comment by gaearon** [comment]
Yep, thanks!

**Pull request merged**
