### PR TITLE
Added Error log

### PR DESCRIPTION
**Pull request by ev1stensberg**
Added error log if user decides to be a superhero.

### CODE REVIEW

**Comment by gaearon** [comment]
I’m a bit confused. `keys` is a local variable obtained from `Object.keys()`. How can the user modify it?
We could potentially warn if `keys` is an empty array but I’m not sure it’s worth the trouble either.

**Comment by ev1stensberg** [comment]
This is just a dummy-check to warn/output something if the user is doing anything that he/she should not do. I added warning at first, but not sure if the user should pass the build if he/she has tweaked it like that. Anyhow, I can change it to warn if the array is empty or if he/she has done anything stupid, but this is a waste of code and it will take space. Anyways, thanks for the response! -Closing this PR.

**Comment by gaearon** [comment]
I think if the user changes the source, they’re on their own. We can’t reliably protect against such cases, and I don’t think we should. I’ve never seen a library do that. I mean, if they want to change how it works, presumably they can also remove any checks we add to prevent this :wink: .

**Comment by ev1stensberg** [comment]
Yeah, true. I think some might have it. In use cases where they want the user to tweak the library on their own while still having a functionality they can follow. But that's extremely rare, I assume :smile:

**Pull request closed without merging**
