### PR TITLE
Add todos example tests

### PR DESCRIPTION
**Pull request by jontewks**
Per issue #1397

### CODE REVIEW

**Comment by jontewks** [comment]
@gaearon wanted to get this opened up for initial review. Originally @urbanvikingr and I were going to pair on these, but my son was born a tad early so I wasn't able to stick to a schedule so we decided to split them. I last heard from @urbanvikingr that he was dealing with some issues and didn't have a lot of spare time about a week ago, so I didn't want this to appear forgotten about. I completed tests for each component, but wanted to leave the option open for @urbanvikingr to contribute some additional test cases, or tests around the container elements if he finds the time.

**Comment by urbanvikingr** [comment]
@jontewks Thank you. I suggest that we merge your additional tests. Then, the `todos` example will have tests for actions, reducers and components.

**Comment by weicheng113** [comment]
Hi Guys,

How these tests are better than the ones in #1463? Have you looked? is it more reasonable to make app easier to test first?

Cheers, Cheng

**Comment by gaearon** [comment]
This looks like a good start to me, please continue!

**Comment by gaearon** [comment]
Hey @jontewks!

We started porting tests to Enzyme (#1481), and @mjw56 submitted a PR handling `todos` as well in #1493. I want to apologize for not handling it better because you already put in some work on this, and I should have notified you about our decision to use Enzyme, and suggest you to work on it first. I’m sorry!

Can you please review #1493 and leave your thoughts on it? Is there anything from here that is missing there?

**Comment by jontewks** [comment]
Thanks @gaearon, and no worries. Sorry this happened so slowly, my wife and I just had a child a tad early so I didn't have nearly the amount of time to put into this as I was hoping. The new tests look good, and I learned from reading through them, like expect has a `createSpy` method, which I could have made use of!

Things have calmed down for us now, so if there is anything else that I can contribute to, I have the spare time this week. Thanks again.

**Comment by mjw56** [comment]
I apologize, I should have gone through the open PR's first before working on this. I'll make sure this does not happen again. Thanks for the feedback @jontewks. I also just reviewed yours as well to make sure we are all on the same page. Again, sorry for the mixup. Congrats on your new child! :smiley:

**Pull request closed without merging**
