### PR TITLE
Add composeReducers util

### PR DESCRIPTION
**Pull request by LucaColonnello**
Add `composeReducers` utility to split complex reducers into multiple chunks handling the same state.

I know this kind of thinks could be a library, but I guess redux should provide a bit more utilities on how to solve some common issues.

This could also help people to avoid write complex reducers and find internal custom solutions to split the code, in favour of an already provided way.

### `reducers/loggedInUser/index.js`

```js
import { composeReducers } from 'redux'
import editInfo from './editInfo';
import uploadPhoto from './uploadPhoto';


const loggedInUser = composeReducers(
  {
    // shared loader for any save or download
    loading: false,

    username: '',
    email: '',
    photos: [],
  },
  editInfo,
  uploadPhoto
)

export default loggedInUser;
```

### `reducers/loggedInUser/editInfo.js`

```js
export default function editInfo(state, action) {
  switch (action.type) {
    // might be an async operation
    case 'EDITING_LOGGED_IN_USER_INFO':
    return {
      ...state,
      loading: true
    }

    case 'SET_LOGGED_IN_USER_USERNAME':
    return {
      ...state,
      loading: false,
      username: action.payload
    }

    case 'SET_LOGGED_IN_USER_EMAIL':
    return {
      ...state,
      loading: false,
      email: action.payload
    }

    default:
    return state
  }
}
```

### `reducers/loggedInUser/uploadPhoto.js`

```js
export default function editInfo(state, action) {
  switch (action.type) {
    case 'UPLOADING_LOGGED_IN_USER_PHOTO':
    case 'DOWNLOADING_LOGGED_IN_USER_PHOTOS':
    return {
      ...state,
      loading: true
    }

    case 'ADD_LOGGED_IN_USER_PHOTO':
    return {
      ...state,
      loading: false,
      photos: [...state.photos, action.payload]
    }

    case 'SET_LOGGED_IN_USER_PHOTOS':
    return {
      ...state,
      loading: false,
      photos: action.payload
    }

    default:
    return state
  }
}
```

### CODE REVIEW

**Comment by markerikson** [comment]
Hi.  First, thanks for the PR.  Looks like you definitely spent some time putting this together, including docs, typings, and tests, so this is certainly a step above the usual "change a couple lines" PR we often get.  So, I appreciate the effort and the interest.

That said, my _first_ reaction is that we'd be unlikely to add any more built-in reducer utilities as part of the core library.  Technically, `combineReducers` itself doesn't even _need_ to be built-in to Redux, but since "slice reducers" are the suggested standard approach, it made sense to include a utility that caters to that use case.

Functionality-wise, this looks almost equivalent to https://github.com/acdlite/reduce-reducers.  The main difference, I think, is that `composeReducers` takes an `initialState` arg, while `reduceReducers` just takes the functions.  

If nothing else, this is at least worth publishing as a utility library.  I have a list of many existing reducer utilities at https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md (a list that _sadly_ needs some cleanup and organization), so there's well-established precedent for people publishing reducer utilities as libraries.

I'll leave this open for discussion for now.

**Comment by gaearon** [comment]
Thanks for the PR but I'd rather not add this to the core. The difference between `compose`, `composeReducers` and `combineReducers` will be a major understanding hurdle for a lot of people. I don't think it is useful enough to offset this problem.

**Comment by LucaColonnello** [comment]
I'll see if I can discuss with @acdlite to address this in his library, maybe make more sense. Thanks for the time spent to review this!

**Comment by markerikson** [comment]
Sure.  Again, this is definitely a good PR overall, just not something we feel is needed in the core.  Thanks!

**Pull request closed without merging**
