### PR TITLE
New documentation on the upcoming GitBook

### PR DESCRIPTION
**Pull request by SamyPesse**
Next week, we'll introduced a new version of GitBook (https://beta.gitbook.com/) 🎉 . This version brings a better reading experience (mobile and desktop), awesome search (powered by Algolia) and some cool new features.

I've run an initial import of the Redux docs in the new GitBook, you can checkout the output at: 
 https://redux.gitbook.io/docs/

It'd be awesome to get your feedback on this new version, and see if you're interested in switching the Redux documentation to this!

[screen shot 2018-02-14 at 18 10 06](https://redux.gitbook.io/docs/)

This version also includes some advanced features to analyse the quality of your documentation: a search dashboard and insights about the quality of your docs:

screen shot 2018-02-14 at 18 02 03
screen shot 2018-02-14 at 18 02 30

### CODE REVIEW

**Comment by timdorr** [comment]
Neat!

Since the CLI tool goes away, do the docs get built on your servers instead? We haven't set it up, but we've always wanted to have automatic docs builds in Travis. If we can make that happen, great!

**Comment by SamyPesse** [comment]
@timdorr Yes, you'll no longer have to run the CLI, the new GitBook will keep the website synced with your GitHub repository!

I can send you an invite (I'll need your email or ping me at samy@gitbook.com).

The next steps if you want to switch are:

1. Merge this PR
2. Use the invite to join the "Redux" organization on beta.gitbook.com
3. Setup the GitBook project to use this repository as a GitHub source
4. Add the `redux.js.org` domain to the GitBook project and update the `redux.js.org` DNS

**Comment by timdorr** [comment]
It's username@username.com. Thanks!

**Comment by timdorr** [comment]
Submitted a request to update the DNS: https://github.com/js-org/dns.js.org/pull/1774

Looks good to me. Let's do this!

**Comment by indus** [comment]
Welcome back https://redux.js.org
(and sorry for the delay)

**Comment by markerikson** [comment]
Not sure I realized we'd actually pulled the trigger and switched.  At first glance, I see two things that are broken:

- All of our pages have had URLs ending with `.html` so far.  , like http://redux.js.org/docs/FAQ.html .  The new site doesn't have `.html` at all, so _every_ external Redux docs link is now presumably a 404.  That's _not_ good, and we need some kind of redirect setup to handle this.
- I had hand-written short anchor tags and TOCs for the FAQ pages.  Those no longer appear to work.  I see that the new site has an auto-generated TOC on the right, but I wanted those short anchors to make it easier to write the URLs.  (For example, handwritten https://redux.js.org/faq/react-redux#react-multiple-components vs auto-generated https://redux.js.org/faq/react-redux#should-i-only-connect-my-top-component-or-can-i-connect-multiple-components-in-my-tree ).

I'm not happy with these differences, and we need to figure out a way to resolve them ASAP.

**Comment by SamyPesse** [comment]
@markerikson 

> All of our pages have had URLs ending with .html so far.

GitBook automatically setups redirects for `.html` to the new urls, for example `https://redux.js.org/faq/immutable-data.html` redirects to `https://redux.js.org/faq/immutable-data`.

The issue come from the `docs/` prefix in previous url. I've missed it in my previous PR. I've opened a PR to fix it: #2843

I'm really sorry about this :(

> I had hand-written short anchor tags and TOCs for the FAQ pages.

We are going to release a fix for this, no action is needed on your side. I'll keep you updated ASAP.

**Pull request merged**
