### PR TITLE
Fix TypeScript tests to pass for new TypeScript definitions

### PR DESCRIPTION
**Pull request by evgenyt1**
Fixed typescript tests for new d.ts
Use prepare instead of prepublish in package.json (same as in master branch).
Update typescript in yarn.lock to comply to what's in package.json

I'm using the `next` branch to have new d.ts and strongly typed actions.

However wondering if the `next` branch is going to be synced with the current master?

### CODE REVIEW

**Comment by timdorr** [comment]
`next` is for proposed 4.0 stuff. It involves a major upgrade of TS, hence it's grouped into that release. No idea when it will land, though.

**Comment by timdorr** [comment]
I just updated the next branch against master. Can you redo this? We're not using yarn now that npm has lockfiles.

**Comment by timdorr** [comment]
BTW, looks like just b9278d1 is all we need in this PR.

**Comment by evgenyt1** [comment]
Just confused. 
Do I understand correctly, that PR https://github.com/reactjs/redux/pull/2674 is merged now and this one mine will be closed?

**Comment by timdorr** [comment]
Yes, sorry, I meant to close this out too. Thanks for the effort!

**Pull request closed without merging**
