### PR TITLE
Apply prettier to docs

### PR DESCRIPTION
**Pull request by CodinCat**
(This PR is related to #2381)

Hi, I applied [Prettier](https://github.com/prettier/prettier) to the code blocks of documentation. Besides, it caught many syntax errors (missing commas, parentheses, fullwidth characters..)  and I have fixed them manually.

Also the [Store type declaration](https://github.com/reactjs/redux/blob/master/docs/Glossary.md#store) in Glossary.md cannot be parsed by prettier. Sorry I'm not familiar with flow, should I add commas to it? Like below:

```js
type Store = {
  dispatch: Dispatch,
  getState: () => State,
  subscribe: (listener: () => void) => () => void,
  replaceReducer: (reducer: Reducer) => void
}
```

### CODE REVIEW

**Comment by timdorr** [comment]
Ho boy, that's a lot of changes...

Any chance you can share your tooling to do this? That actually sounds like a really cool project to run prettier on code blocks in a markdown doc. I'd encourage you to publish it!

As for the Glossary, I wouldn't worry about that. It's only a loose typing, not comprehensive. It's mainly there for explanatory reasons, so having perfect formatting isn't a requirement.

Since this is a lot of changes, some of which revert intentional style deviations, what if we break this up into more manageable chunks? I still publish the docs manually, so it wouldn't be published until everything is buttoned up and good to go. Maybe by folder?

**Comment by CodinCat** [comment]
Actually it's just a very rough and ugly script I wrote for this. But sure, I can spend some time to cleanup the code and publish it.

Did you mean I should break this PR to smaller ones so you can merge them progressively? Should I just open several PRs or is there any better way to do that? thanks.

**Comment by timdorr** [comment]
Yeah, just several PRs will work. Should only be a handful of them. We've got thousands, so what are a few more? 😄

**Comment by timdorr** [comment]
Closing in favor of the other PRs.

**Pull request closed without merging**
