### PR TITLE
Fix redux-mock-store libdef for todos-flow

### PR DESCRIPTION
**Pull request by lifeiscontent**
Just updating a libdef to keep todos-flow at 100%

### CODE REVIEW

**Comment by timdorr** [comment]
Hmm, this is going to get annoying. Are we sure we can't just dynamically pull the typedefs at build/test time?

**Comment by lifeiscontent** [comment]
@timdorr should I just add a post install script for the package.json?

**Comment by timdorr** [comment]
Yeah, that's probably going to be best. Manually maintaining these files is going to create a lot of noise in the commits over time.

**Comment by lifeiscontent** [comment]
@timdorr all updated 👍

**Comment by timdorr** [comment]
Awesome! Thanks!

**Pull request merged**
