### PR TITLE
human readable compose.js

### PR DESCRIPTION
**Pull request by mondaychen**
A more readable compose.js with some lodash utils.

### CODE REVIEW

**Comment by gaearon** [comment]
Importing them from `lodash` top-level export rather than through individual modules is going to dramatically increase the UMD build size because it will bundle the whole Lodash with Redux. This is definitely not we want.

Even importing these modules directly, the utlities you use here will add a lot of code to Redux that we don’t actually need. You can verify it yourself by running `npm run build` and checking the size of the compiled bundle. I’m closing for this reason.

Thanks you for sending a PR!

**Comment by gaearon** [comment]
I’m up for replacing `(...args) => args[0]` with `arg => arg` though!

**Comment by mondaychen** [comment]
@gaearon understood. And I will only replace `...args` https://github.com/reactjs/redux/pull/1622

**Comment by gaearon** [comment]
Thanks!

**Pull request closed without merging**
