### PR TITLE
Fix redirects in docs for previous urls

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR fixes the issue about urls mentioned in #2837 and #2842.

You can test it on the test project (https://redux.gitbook.io/redux-test/) which is synced with my fork `SamyPesse/redux`:

- https://redux.gitbook.io/redux-test/docs/introduction/index.html
- https://redux.gitbook.io/redux-test/docs/basics/index.html
- https://redux.gitbook.io/redux-test/docs/advanced/index.html
- https://redux.gitbook.io/redux-test/docs/recipes/index.html
- https://redux.gitbook.io/redux-test/docs/Glossary.html

### CODE REVIEW

**Comment by markerikson** [comment]
Cool, let's get this merged in now.

Per Tim's other comment, can you also fix the "Edit on Github" links to point to our main repo instead of your fork?  Let's do that as a separate PR.

**Comment by SamyPesse** [comment]
The "Edit on GitHub" link still points to my repository because the GitBook space is still linked to my fork.

One of you (@markerikson or @timdorr ) needs to go to https://redux.js.org/~/settings/integrations (as a space admin) and setup the GitHub integration with this repository.

**Comment by SamyPesse** [comment]
The previous urls are now working correctly: http://redux.js.org/docs/api/index.html 🎉 

Let me know if you need help configuring the GitHub integration at https://redux.js.org/~/settings/integrations

You can ping me using the Intercom widget on https://beta.gitbook.com

**Comment by markerikson** [comment]
Yep, sweet!  Thanks for the quick fix and directions on the integration.

Now we just need the FAQ anchor links fixed up - you said that was something on your end?

**Comment by SamyPesse** [comment]
The new GitBook is not generating raw HTML from the markdown parsing, but instead parse it as a semantic JSON document. HTML in markdown is stripped from the output.

You were using raw HTML (`<a id="..."></a>`) to have anchors in the document. But it's hacky because GitHub doesn't support to define custom IDs on headings.

Our markdown parser supports the [Kramdown syntax for custom IDs](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id): `# Hello {#mycustom-id}`. But it doesn't render well on GitHub.

I'll discuss this issue tomorrow with the rest of the team, and we'll come up with a solution that works for you. We'll probably extend our parsing to detect these `<a id="..."></a>` and reattach them to the headers; in that case it'll require no work on your end.

Anyway this is a common use-case and we should have a clear solution for it!

I'll keep you updated ASAP.

**Comment by markerikson** [comment]
Yeah, I figured it was something like that.  I'm fine with tweaking the way we define those links if there's a better option.

Appreciate you looking into this!

**Pull request merged**
