### PR TITLE
Snapshot tests

### PR DESCRIPTION
**Pull request by Hemko**
#2184 

Added snapshot tests (todomvc and tree-view examples).
https://github.com/reactjs/redux/issues/2184#issuecomment-271313696

### CODE REVIEW

**Comment by brigand** [comment]
I don't think **replacing** tests with snapshots is good. They should be in addition to manual tests.

**Comment by Hemko** [comment]
Hm... I thought it was means replacing, not adding.

> Try to find some tests that are checking output and change them to snapshot tests.

Ok, i can just add this tests.

Also, i got some troubles. Why this happens?
```
- Snapshot
+ Received

- onChange={[Function mockConstructor]}
+ onChange={[Function anonymous]}
```

**Comment by brigand** [comment]
I think the CI build failures are because of the difference between these in ES5, but them being the same in ES6:

```js
var f = function() {};
var f = function f() {}
```

I'm not sure why babel-jest isn't fixing this.

**Comment by Hemko** [comment]
@brigand Now it's ok?

**Comment by brigand** [comment]
@Hemko looks good to me, but I'm not an authority on this repo. 

For older node versions, what about just disabling snapshots on them? Since there are other tests, it's not a big deal.

**Comment by Hemko** [comment]
@brigand 
Can you suggest the correct way to disabling snapshots for older node version?
I tried this way:
`      if (nodeMajorVersion > 5) {
        expect(output).toMatchSnapshot()
      }
`
But i got the next result:
> 16 obsolete snapshots -> snapshot failure

**Comment by brigand** [comment]
@Hemko apparently this is supposed to be [fixed already](https://github.com/facebook/jest/issues/2618). Try `yarn add jest@18.0.0. I have that version at work and it works correctly. 18.1.0 is currently installed here according to yarn.lock.

For now, we could create a helper that recursively iterates over the output and replace each function with `function f(){}`.

**Comment by Hemko** [comment]
@brigand
What did you mean under helper?
Function which will change the render output?

**Comment by brigand** [comment]
@Hemko on second thought, filtering out the function props would be a pretty crazy solution. By helper I just meant a function that the tests could use to augment the output.

**Comment by Hemko** [comment]
@brigand I don't know how to do that. Can you show some examples?

**Comment by Hemko** [comment]
Perhaps someone knows how to fix this problem?

Additional Information:
https://github.com/facebook/jest/issues/1681

**Pull request closed without merging**
